### ISSUE TITLE
Step 5: `on-click` instead of `on-tap` is being leveraged; any particular reason? 

### ISSUE THREAD

**Issue by lozandier** [blasten/pwa-from-scratch#4]
It seems Step 5 is deliberately violating leveraging `on-tap` semantics of dealing with click events that's seemingly often a best practice with Polymer instead of reacting to click events 

Is this deliberate?

**Comment by blasten** [comment]
Yep. `tap` used to solve the 300ms click delay in mobile Chrome/Safari, but that isn't longer an issue in the browsers we support. So, use the platform when it works! `on-click`
